### ISSUE TITLE
generate button not working

### ISSUE THREAD

**Issue by sandeshkoiralaa** [zalazarc20/tiktokDL#1]
i tried this code in my localhost and generate button does not work

**Comment by zalazarc20** [comment]
Hello, thanks for telling me about your problem.
Have you tried to change the generate button?

You could replace the button with an input of type submit, that is to say, to pass from this 

```<button id="submit" type="submit" class="btn-submit">GENERATE</button>``` 

to this other

 ```<input type="submit" id="submit" class="btn-submit" value="GENERATE">```

**Comment by sandeshkoiralaa** [comment]
> Hello, thanks for telling me about your problem. Have you tried to change the generate button?
> 
> You could replace the button with an input of type submit, that is to say, to pass from this
> 
> `<button id="submit" type="submit" class="btn-submit">GENERATE</button>`
> 
> to this other
> 
> `<input type="submit" id="submit" class="btn-submit" value="GENERATE">`

**Comment by sandeshkoiralaa** [comment]
thank you so much it's working but I'm having a problem with API 
    let domain = 'https://www.tikwm.com/';
  
I tried to remove this but the whole website went down 
what is tikwn.com doing in this code can you explain me this in brief?

**Comment by zalazarc20** [comment]
> muchas gracias está funcionando pero tengo un problema con la API let domain = ' https://www.tikwm.com/ ';
> 
> Traté de eliminar esto, pero todo el sitio web se cayó. ¿Qué está haciendo tikwn.com en este código? ¿Puede explicarme esto brevemente?

The domain variable has the url from where that data is extracted (remember that this is a scrapper from another website).

The first is to go through the axios request and the second is to get the data that is sent to the client.
if you want to remove the domain variable remember at the end of the code you are using it to get the links 
![alt text for screen readers](https://i.imgur.com/hpYsaZx.png "Text to show on mouseover")

**Comment by sandeshkoiralaa** [comment]
do I get a copyright issue if I launch the website with this code?

**Comment by zalazarc20** [comment]
> ¿Tengo un problema de derechos de autor si abro el sitio web con este código?

you are free to use this project however you want, it is copyright free 😁

**Comment by sandeshkoiralaa** [comment]
using the domain https://www.tikwm.com in my code does not hamper my website right?

**Comment by zalazarc20** [comment]
> using the domain https://www.tikwm.com in my code does not hamper my website right?

this project is a scrapper from another website, if you want to avoid having to use that domain I recommend you look for a premium api. 
you can investigate more in [rapidApi](https://rapidapi.com/hub)
