### ISSUE TITLE
API

### ISSUE THREAD

**Issue by sandeshkoiralaa** [zalazarc20/tiktokDL#5]
how can I change the custom API I recently got approved on the TikTok developers program.

**Comment by zalazarc20** [comment]
> ¿Cómo puedo cambiar la API personalizada que recientemente me aprobaron en el programa de desarrolladores de TikTok?

Hello, this application works by scraping another page.
If you want to change the API, I recommend you to modify the tiktokDL.js file.

**Comment by sandeshkoiralaa** [comment]
> > ¿Cómo puedo cambiar la API personalizada que recientemente me aprobaron en el programa de desarrolladores de TikTok?
> 
> Hello, this application works by scraping another page. If you want to change the API, I recommend you to modify the tiktokDL.js file.

can i use this code to make my own tiktok video downloader website??

**Comment by zalazarc20** [comment]
> > > ¿Cómo puedo cambiar la API personalizada que recientemente me aprobaron en el programa de desarrolladores de TikTok?
> > 
> > 
> > Hola, esta aplicación funciona raspando otra página. Si desea cambiar la API, le recomiendo que modifique el archivo tiktokDL.js.
> 
> ¿Puedo usar este código para hacer mi propio sitio web de descarga de videos tiktok?

If you can use this code to create your own website (for me, no problem), but keep in mind that the download links have the domain of the other website.

**Comment by sandeshkoiralaa** [comment]
> 

how can i change that?

**Comment by sandeshkoiralaa** [comment]
> > > > ¿Cómo puedo cambiar la API personalizada que recientemente me aprobaron en el programa de desarrolladores de TikTok?
> > > 
> > > 
> > > Hola, esta aplicación funciona raspando otra página. Si desea cambiar la API, le recomiendo que modifique el archivo tiktokDL.js.
> > 
> > 
> > ¿Puedo usar este código para hacer mi propio sitio web de descarga de videos tiktok?
> 
> If you can use this code to create your own website (for me, no problem), but keep in mind that the download links have the domain of the other website.

how can i change that?

**Comment by zalazarc20** [comment]
> > > > > ¿Cómo puedo cambiar la API personalizada que recientemente me aprobaron en el programa de desarrolladores de TikTok?
> > > > 
> > > > 
> > > > Hola, esta aplicación funciona raspando otra página. Si desea cambiar la API, le recomiendo que modifique el archivo tiktokDL.js.
> > > 
> > > 
> > > ¿Puedo usar este código para hacer mi propio sitio web de descarga de videos tiktok?
> > 
> > 
> > Si puedes usar este código para crear tu propia web (para mí no hay problema), pero ten en cuenta que los enlaces de descarga tienen el dominio de la otra web.
> 
> ¿Cómo puedo cambiar eso?

You could create a custom route with express, that avoids showing the other website's domain 🤔.

Or else, you can investigate some API on the page [rapidAPI](https://rapidapi.com/hub)
